version: "3.0"
services:
  currency-exchange-app:
    container_name: currency-exchange
    image: currency-exchange
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
  db:
    container_name: "db"
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
